import nodemailer from 'nodemailer';
import { getSettings } from './settings.js';

/**
 * Get configured Nodemailer transporter.
 */
function getTransporter(settings) {
  if (!settings.smtpHost || !settings.smtpUser) {
    throw new Error('SMTP settings incomplete.');
  }
  
  return nodemailer.createTransport({
    host: settings.smtpHost,
    port: parseInt(settings.smtpPort || '587', 10),
    secure: parseInt(settings.smtpPort, 10) === 465, // true for 465, false for 587
    auth: {
      user: settings.smtpUser,
      pass: settings.smtpPass,
    },
  });
}

/**
 * Test SMTP connection by sending a simple test email.
 */
export async function testEmailConfig(workspaceId, uiSettings) {
  const dbSettings = await getSettings(workspaceId);
  const settings = { ...dbSettings, ...uiSettings };
  
  const transporter = getTransporter(settings);
  await transporter.verify();

  const to = settings.digestEmail || settings.smtpUser;
  if (!to) throw new Error('No recipient email configured.');

  const info = await transporter.sendMail({
    from: `"LegisTracker" <${settings.smtpUser}>`,
    to,
    subject: 'LegisTracker SMTP Test',
    text: 'If you are reading this, your LegisTracker SMTP settings are working correctly!',
    html: '<div style="font-family: sans-serif; text-align: center; padding: 20px;"><h2>✅ SMTP Test Successful</h2><p>Your LegisTracker email configuration is working.</p></div>',
  });

  return info;
}

/**
 * Build the HTML content for the digest email.
 * @param {object} data - { newBills, changedBills, matches, upcomingEvents }
 */
export function buildDigestHtml(data) {
  const { newBills = [], changedBills = [], matches = [], upcomingEvents = [] } = data;
  
  if (newBills.length === 0 && changedBills.length === 0 && matches.length === 0 && upcomingEvents.length === 0) {
    return null; // Nothing to report
  }

  const billRow = (b) => `
    <div style="margin-bottom: 12px; padding: 12px; border: 1px solid #e2e8f0; border-radius: 6px; background: #f8fafc;">
      <div style="font-weight: bold; color: #0f172a; margin-bottom: 4px;">
        <span style="display: inline-block; padding: 2px 6px; background: #e2e8f0; border-radius: 4px; font-size: 11px; margin-right: 6px;">${b.jurisdiction}</span>
        ${b.number}
      </div>
      <div style="color: #334155; font-size: 14px;">${b.title}</div>
      ${b.reason ? `<div style="color: #64748b; font-size: 13px; margin-top: 4px;"><em>${b.reason}</em></div>` : ''}
    </div>
  `;

  return `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; line-height: 1.5; color: #334155;">
      
      <div style="background: #1e293b; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0; font-size: 20px;">🏛️ LegisTracker Digest</h1>
        <div style="font-size: 13px; opacity: 0.8; margin-top: 4px;">${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</div>
      </div>

      <div style="padding: 24px; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 8px 8px; background: white;">
        
        ${matches.length > 0 ? `
          <h2 style="font-size: 16px; color: #b91c1c; border-bottom: 2px solid #fee2e2; padding-bottom: 8px; margin-bottom: 16px;">🔍 Keyword Matches (${matches.length})</h2>
          ${matches.map(billRow).join('')}
        ` : ''}

        ${changedBills.length > 0 ? `
          <h2 style="font-size: 16px; color: #b45309; border-bottom: 2px solid #fef3c7; padding-bottom: 8px; margin-bottom: 16px; margin-top: 32px;">📝 Changed Bills (${changedBills.length})</h2>
          ${changedBills.map(billRow).join('')}
        ` : ''}

        ${upcomingEvents.length > 0 ? `
          <h2 style="font-size: 16px; color: #1d4ed8; border-bottom: 2px solid #dbeafe; padding-bottom: 8px; margin-bottom: 16px; margin-top: 32px;">📅 Upcoming Hearings & Events (${upcomingEvents.length})</h2>
          ${upcomingEvents.slice(0, 10).map(e => `
            <div style="margin-bottom: 8px; font-size: 14px;">
              <strong>${e.date} ${e.time ? `at ${e.time}` : ''}</strong>: 
              ${e.billId ? `[Bill ${e.billId}] ` : ''}${e.description}
              <span style="color: #64748b; font-size: 13px;">— ${e.location}</span>
            </div>
          `).join('')}
        ` : ''}

        ${newBills.length > 0 ? `
          <h2 style="font-size: 16px; color: #15803d; border-bottom: 2px solid #dcfce3; padding-bottom: 8px; margin-bottom: 16px; margin-top: 32px;">📄 New Tracked Bills (${newBills.length})</h2>
          ${newBills.map(billRow).join('')}
        ` : ''}

        <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 12px; color: #94a3b8;">
          This digest was automatically generated by your LegisTracker instance.<br>
          <a href="http://localhost:3000/settings" style="color: #64748b;">Manage Digest Settings</a>
        </div>
      </div>
    </div>
  `;
}

/**
 * Send the digest email.
 */
export async function sendDigest(workspaceId, data) {
  const settings = await getSettings(workspaceId);
  if (settings.digestFrequency === 'disabled' || !settings.digestEmail) {
    return { skipped: true, reason: 'Disabled or no recipient' };
  }

  const html = buildDigestHtml(data);
  if (!html) {
    return { skipped: true, reason: 'No new data to report' };
  }

  const transporter = getTransporter(settings);
  await transporter.sendMail({
    from: `"LegisTracker Digest" <${settings.smtpUser}>`,
    to: settings.digestEmail,
    subject: `LegisTracker: ${data.matches?.length || 0} Matches, ${data.upcomingEvents?.length || 0} Events`,
    html,
  });

  return { success: true, sentAt: new Date().toISOString() };
}
